update gcp-documentation
ssc-spc-ccoe-cei/gcp-documentation pull request #11
Opened 2023-02-15 15:25 UTC by ovidiuasiminei-ssc

2023-02-15 15:56 UTC, alaincormier-ssc commented on Architecture/Repository Structure.md
> +1. For each environment (experimentation, dev, uat, prod), check if `source-customization/` contains that sub directory.  If so:
the hydrate.sh script and repo folders are not yet updated to use the new name, maybe we should keep sandbox until they're updated?

2023-02-15 16:01 UTC, ovidiuasiminei-ssc commented on Architecture/Repository Structure.md
> +1. For each environment (experimentation, dev, uat, prod), check if `source-customization/` contains that sub directory.  If so:
Yes I don't changed. I think is best to keep until they're are updated . Thanks Alain

2023-02-15 16:03 UTC, alaincormier-ssc commented
the `Building_Using_Automation.md` will also need an update to a sandbox package

2023-02-15 19:50 UTC, davelanglois-ssc commented on Architecture/Repository Structure.md
> +1. For each environment (experimentation, dev, uat, prod), check if `source-customization/` contains that sub directory.  If so:
we are going forward with the modification of the documentation.  @ovidiuasiminei-ssc will create PR for gcp-tools and gcp-repo-template

2023-02-15 20:04 UTC, ovidiuasiminei-ssc commented on Architecture/Repository Structure.md
> +1. For each environment (experimentation, dev, uat, prod), check if `source-customization/` contains that sub directory.  If so:
Thanks Dave, I will create PR for gcp-tools and gcp-repo-teplate

2023-02-15 21:40 UTC, davelanglois-ssc commented on Architecture/Repository Structure.md
> +    - `gcp-sandbox-tier1-infra` contains the landing zone configs for experimentation.
rename repo

2023-02-15 21:43 UTC, davelanglois-ssc commented on Developer/Guide.md
> +The diagram below describes the naming convention for repositories and uses NRCan, as a client, to provide examples.
The diagram below describes the naming convention for repositories and uses na, as a client code, to provide examples

2023-02-15 21:47 UTC, davelanglois-ssc commented on Onboarding/Tenant.md
> +   For example, when creating a client folder to represent Shared Services Canada, employ both the official English and French abbreviation separated by a dash (e.g. SSC-SPC).
please use lower case...e.g. .ssc-spc

2023-02-15 21:48 UTC, davelanglois-ssc commented on Onboarding/Tenant.md
> +      kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/hierarchy/client-sandbox@main ./landing-zone/hierarchy/clients/<client name>
replace client-sandbox

2023-02-15 21:52 UTC, davelanglois-ssc commented on Onboarding/Workload.md
> +      kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/project/project-experimentation@main ./landing-zone/hierarchy/clients/<client name>/Workloads/<projec
@uday needs to update that package

2023-02-15 21:53 UTC, davelanglois-ssc commented on Onboarding/Workload.md
> +      kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/project/project-experimentation@main ./landing-zone/hierarchy/clients/<client name>/Workloads/<projec
rename Workloads accordingly

2023-02-15 21:53 UTC, davelanglois-ssc commented on Onboarding/Workload.md
> +      kpt pkg get https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit.git/solutions/project/project-experimentation@main ./landing-zone/hierarchy/clients/<client name>/Workloads/<data c
rename Workloads

2023-02-15 21:54 UTC, davelanglois-ssc commented on Onboarding/Workload.md
> +## Add client's workload to the landing zone repository
rename workload

2023-02-15 21:55 UTC, davelanglois-ssc commented
@ovidiuasiminei-ssc also rename onboarding/Tenant.md to client.md and Workload.md to application.md

2023-02-16 18:25 UTC, davelanglois-ssc submitted a review, later dismissed

2023-02-16 19:15 UTC, alaincormier-ssc commented
hydrate.sh will now be updated to use experimentation instead of sandbox, same with the template repo.
there are reference to sandbox in these files:
- Changing.md
- Repositories.md

2023-02-16 19:19 UTC, alaincormier-ssc commented on Landing Zone Operations/Building_Using_Automation.md
>          repo name = `gcp-sandbox-tier1-infra`
`gcp-sandbox-tier1-infra` should be `gcp-experimentation-tier1-infra`

also see my previous [comment](https://github.com/ssc-spc-ccoe-cei/gcp-documentation/pull/11#issuecomment-1433589907) for `Changing.md` and `Repositories.md`.
thanks

2023-02-16 19:28 UTC, ovidiuasiminei-ssc commented on Landing Zone Operations/Building_Using_Automation.md
>          repo name = `gcp-sandbox-tier1-infra`
Thanks Alain, Done !

2023-02-16 19:34 UTC, uday-ssc commented
@ovidiuasiminei-ssc  the branch name should be github specific issue , not sure if we want to strictly follow the convention tho.

2023-02-16 19:40 UTC, ovidiuasiminei-ssc commented
I was looking what branch we have

***@***.***:~/code/gcp-documentation$ git branch -a
* az4314-gcp-doc
  main
  remotes/origin/HEAD -> origin/main
  remotes/origin/az3190-dave
  remotes/origin/az3190-update-setup-kcc
  remotes/origin/az3573-gator-cli
  remotes/origin/az3625-docs-repos
  remotes/origin/az4314-gcp-doc
  remotes/origin/doc/gcpboard-4006
  remotes/origin/main

On Thu, Feb 16, 2023 at 2:34 PM uday-ssc ***@***.***> wrote:

> @ovidiuasiminei-ssc <https://github.com/ovidiuasiminei-ssc> the branch
> name should be github specific issue , not sure if we want to strictly
> follow the convention tho.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ssc-spc-ccoe-cei/gcp-documentation/pull/11#issuecomment-1433610078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4KFO3EUNZ6AKI4R4LL75JTWXZ6MJANCNFSM6AAAAAAU47VOPQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-16 19:41 UTC, uday-ssc commented
@ovidiuasiminei-ssc  some files are not in review , but need to change , 
1. Organizations.png (developer/img) - this image has to change
2. 
![image](https://user-images.githubusercontent.com/100966603/219469520-143caa16-1222-4d0a-87d7-1f9c327a8968.png)
this has to be experimentation-networking

3.
![image](https://user-images.githubusercontent.com/100966603/219469723-ee76c620-beac-46e3-83f8-806d0f05534c.png)
this image is incorrect

2023-02-16 20:09 UTC, uday-ssc requested changes

2023-02-16 20:21 UTC, ovidiuasiminei-ssc commented on Onboarding/Tenant.md
> +# Client Onboarding
The file name is Client.md

https://github.com/ssc-spc-ccoe-cei/gcp-documentation/pull/11/files/3d57a6a9e409a151817aa58ba368dbfebfa809db

2023-02-16 20:28 UTC, ovidiuasiminei-ssc commented on Onboarding/Admin.md
> +1. locally clone the experimentation landing zone repo
Fixed

2023-02-16 20:32 UTC, ovidiuasiminei-ssc commented on Onboarding/Admin.md
>  1. create a branch of main
Fixed

2023-02-16 20:42 UTC, ovidiuasiminei-ssc commented on Onboarding/Admin.md
>  ## Add admin folder(s) to the landing zone repository
Fixed

2023-02-16 20:49 UTC, ovidiuasiminei-ssc commented on Developer/Guide.md
> +The diagram below describes the naming convention for repositories and uses na, as a client, to provide examples.
fixed

2023-02-16 20:50 UTC, ovidiuasiminei-ssc commented on Onboarding/Application.md
> +1. Naming convention for project-id : `<client-code><environment-code><region-code><data-classification>`-`<project-owner>`-`<user defined string>`
Fixed

2023-02-17 12:31 UTC, davelanglois-ssc commented
> ame should be github specific iss

@ovidiuasiminei-ssc @uday-ssc Well, I believe this is not the case for our SSC repos. Right now, we don't have any issues open on our repos so we can avoid that burden of replicating the azure devops storys into github and just use the azdo story number for the branches. The situation is different on the pubsec repos as this is a repo with an existing long list of issues and, it also has much more visibility than ours meaning that we will put in the additional effort of generating a github issue for the azdo stories. Starting next sprint, @cheffj  will be responsible of tracking/synching azdo/github for the pubsec repo

2023-02-17 17:18 UTC, uday-ssc approved these changes

2023-02-17 17:44 UTC, davelanglois-ssc approved these changes

2023-02-17 17:46 UTC, merged