add doc colection1
ssc-spc-ccoe-cei/gcp-documentation pull request #18
Opened 2023-03-21 14:19 UTC by ovidiuasiminei-ssc

Added :
  -  Config Controller 
  - Firewall Rules Creation
  - IAP access into a VM 
  - Cloud Load Balancing

2023-03-21 21:00 UTC, Michael-McAuley-SSC commented on Architecture/Addendum.md
> +#### [VPC firewall rules overview](https://cloud.google.com/vpc/docs/firewalls)
Rules Overview

2023-03-21 21:01 UTC, Michael-McAuley-SSC commented on Architecture/Addendum.md
> +#### [Cloud Load Balancing overview](https://cloud.google.com/load-balancing/docs/load-balancing-overview)
caps

2023-03-21 21:01 UTC, Michael-McAuley-SSC commented on Architecture/Addendum.md
> +#### [IAP TCP forwarding overview](https://cloud.google.com/compute/docs/instances/connecting-to-windows#remote-desktop-connection-app)
Overview

2023-03-21 21:25 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +
done

2023-03-21 21:25 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +#### [VPC firewall rules overview](https://cloud.google.com/vpc/docs/firewalls)
done

2023-03-21 21:25 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +#### [Cloud Load Balancing overview](https://cloud.google.com/load-balancing/docs/load-balancing-overview)
done

2023-03-21 21:26 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +#### [IAP TCP forwarding overview](https://cloud.google.com/compute/docs/instances/connecting-to-windows#remote-desktop-connection-app)
done

2023-03-21 21:34 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +Virtual Private Cloud (VPC) firewall rules apply to a given project and network. If you want to apply firewall rules to multiple VPC networks in an organization.
Is not .

2023-03-21 21:35 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +### Policy controller
done

2023-03-21 21:35 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +#### [Config Controller overview](https://cloud.google.com/anthos-config-management/docs/concepts/config-controller-overview)
done

2023-03-22 12:55 UTC, lucstjean-ssc commented on Architecture/Addendum.md
> +Virtual Private Cloud (VPC) firewall rules apply to a given project and network. If you want to apply firewall rules to multiple VPC networks in an organization.
I agree with Michael. 

If you want to apply firewall rules to multiple VPC networks in an organization (then what do you do?)

2023-03-22 13:18 UTC, davelanglois-ssc commented on Architecture/Addendum.md
> +### IAP access into a VM
I think the title should be ... into a windows VM

2023-03-22 13:22 UTC, davelanglois-ssc commented on Architecture/Addendum.md
> +#### [IAP TCP Forwarding Overview](https://cloud.google.com/compute/docs/instances/connecting-to-windows#remote-desktop-connection-app)
this link is for windows vm access and not for tcp forwarding. this link is for iap tcp forwarding https://cloud.google.com/iap/docs/tcp-forwarding-overview

2023-03-22 13:24 UTC, davelanglois-ssc commented on Architecture/Addendum.md
> +### Set up Config Controller
adjust table of content

2023-03-22 13:32 UTC, alaincormier-ssc commented on Architecture/Addendum.md
> +### IAP access into a VM
maybe the titles and/or paragraphs in this section are reversed?

2023-03-22 13:47 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +### Set up Config Controller
Thanks, Dave.

2023-03-22 15:17 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +Virtual Private Cloud (VPC) firewall rules apply to a given project and network. If you want to apply firewall rules to multiple VPC networks in an organization.
Fixed .

2023-03-22 15:17 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +### IAP access into a VM
fixed

2023-03-22 16:28 UTC, lucstjean-ssc commented on Architecture/Addendum.md
> +Virtual Private Cloud (VPC) firewall rules apply to a given project and network. If you want to apply firewall rules to multiple VPC networks in an organization, see [Firewall policies](https://cloud
Missing a period (.) at the end of this line :)

2023-03-22 17:02 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +Virtual Private Cloud (VPC) firewall rules apply to a given project and network. If you want to apply firewall rules to multiple VPC networks in an organization, see [Firewall policies](https://cloud
OK, Thanks :)

2023-03-24 13:55 UTC, davelanglois-ssc commented on Architecture/Addendum.md
> +Virtual Private Cloud (VPC) firewall rules apply to a given project and network. If you want to apply firewall rules to multiple VPC networks in an organization.
The original sentence from google cloud documentation is "If you want to apply firewall rules to multiple VPC networks in an organization, see [Firewall policies](https://cloud.google.com/vpc/docs/firewall-policies-overview)". we don't need to provide information on firewall policies as it is not something we use in the landing zone. Please remove that sentence.

2023-03-24 14:07 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +Virtual Private Cloud (VPC) firewall rules apply to a given project and network. If you want to apply firewall rules to multiple VPC networks in an organization.
done

2023-03-24 14:12 UTC, davelanglois-ssc commented on Architecture/Addendum.md
> +### IAP access into a windows VM
please create a parent section called "Remote Access with IAP" and have the "IAP access into a windows VM" section and the "IAP TCP Forwarding Overview" section as subsections to this new parent

2023-03-27 19:39 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
> +### IAP access into a windows VM
done

2023-03-27 19:40 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
done

2023-03-28 11:35 UTC, davelanglois-ssc approved these changes

2023-03-28 13:29 UTC, lucstjean-ssc approved these changes
/lgtm

2023-03-28 13:38 UTC, merged

2023-03-28 13:42 UTC, Michael-McAuley-SSC requested changes
Just that one link that seems to be missing, then can be approved.

2023-03-28 13:42 UTC, Michael-McAuley-SSC commented on Architecture/Addendum.md
> +
extra blank line

2023-03-28 13:42 UTC, Michael-McAuley-SSC commented on Architecture/Addendum.md
>  Check your regions latency using [GPCping](https://gcping.com/)
Missing:
The ultimate [infographic on GCP products](https://googlecloudcheatsheet.withgoo/

2023-03-28 13:57 UTC, ovidiuasiminei-ssc commented on Architecture/Addendum.md
>  Check your regions latency using [GPCping](https://gcping.com/)
The link exist.